[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --html=results/report.html
    --self-contained-html
    -ra
    --strict-markers

markers =
    api: API tests
    ui: UI tests

