
name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
     browser:
       description: "Browser to run tests"
       required: true
       default: "chrome"

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements
          pip install pytest

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Cache workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  test:
    runs-on: ubuntu-latest
    needs: setup
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
  
      # Cache pip packages
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  
      - name: Install dependencies
        run: |
          pip install -r requirements
  
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run tests
        run: pytest tests/ -v tests/

      - name: Upload raw test data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: reports/

  report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-output

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: final-reports
          path: reports/
          
      # Show results directly in GitHub UI
      - name: Publish Test Results
        if: ${{ always() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            test-results/**/*.xml
            
  cleanup:
    runs-on: ubuntu-latest
    needs: report
    if: always()

    steps:
      - name: Cleanup info
        run: echo "Cleanup completed"


